# Default values for hello-world-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: reversaidx/nodejs-test
  tag: v2
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: LoadBalancer
  ports:
    - name: "api"
      protocol: TCP
      containerPort: 3000
    - name: "client"
      protocol: TCP
      containerPort: 4000

env: 
  API_HOST: http://localhost:3000
  ADMIN_EMAIL: test
  ADMIN_PASSWORD: 123
  MONTHS: test
  ENABLE_TOS_SECURE_CHANGE: TEST
  VENDOR_COMPANY: test
  END_COMPANY: test
  ACCOUNT_API_KEY: 0P7V0JDUWO8X257OOZYTYY9ZFPCLEMVQ

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

mongo:
  enabled: true
  image: mongo:latest
  